datasources:
  default:
    url: jdbc:tc:oracle:///xepdb1
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: test
    password: test

micronaut:
  server:
    port: 0

endpoints:
  all:
    port: 0
    enabled: false
